// GENERATED by scripts/gen_briefing_types.py — DO NOT EDIT BY HAND.
// Regenerate after a briefing_model.py change: python3 scripts/gen_briefing_types.py
// Source of truth: OperativeBriefingBundle.model_json_schema() (Pydantic v2).

export interface AlgoEdge {
  src: string
  dst: string
  condition?: string
}

export interface AlgoNode {
  id: string
  label: string
  kind?: "decision" | "action" | "terminal"
}

export interface BriefingFigure {
  fig_id: string
  image_path: string
  caption?: string
  citation?: string
  intent?: string
  generated?: boolean
  source_n?: string
}

export interface BriefingItem {
  text: string
  priority?: "critical" | "high" | "optional"
  source_refs?: string[]
  unsupported?: boolean
}

export interface BriefingProvenance {
  textbook_ok?: boolean
  literature_ok?: boolean
  degraded?: boolean
  reason?: string
  failed_sections?: string[]
  model?: string
}

export interface BriefingReference {
  ref_id: string
  kind: "textbook" | "pubmed"
  citation: string
  meta?: Record<string, unknown>
  sections?: string[]
}

export interface BriefingSection {
  key: string
  title: string
  items?: BriefingItem[]
  note?: string
}

export interface CranialEquipment {
  kind?: "cranial"
  head_fixation?: string[]
  visualization_navigation?: string[]
  monitoring?: string[]
  instruments_clips?: string[]
  graft_reconstruction?: string[]
  contingency?: string[]
  source_refs?: string[]
}

export interface DecisionAlgorithm {
  nodes?: AlgoNode[]
  edges?: AlgoEdge[]
}

export interface EndovascularEquipment {
  kind?: "endovascular"
  access_strategy?: string[]
  catheters_wires?: string[]
  devices?: string[]
  antithrombotic?: string[]
  closure?: string[]
  bailout_access_alt?: string[]
  source_refs?: string[]
}

export interface OperativeBriefing {
  title: string
  sections?: BriefingSection[]
  algorithm?: DecisionAlgorithm | null
  modalities?: TreatmentModality[]
  equipment?: CranialEquipment | SpineEquipment | EndovascularEquipment | null
  unknowns?: string[]
  disclaimer?: string
}

export interface SpineEquipment {
  kind?: "spine"
  positioning_monitoring?: string[]
  decompression_fusion_tools?: string[]
  instrumentation_system?: string[]
  cage_class_sizing?: string[]
  graft_options?: string[]
  navigation_robotics_fluoro?: string[]
  backup_salvage?: string[]
  source_refs?: string[]
}

export interface TreatmentModality {
  name: string
  role?: string
  advantages?: string[]
  limitations?: string[]
  favoring?: string[]
  preferred?: boolean
  source_refs?: string[]
}

export type EquipmentPlan = CranialEquipment | SpineEquipment | EndovascularEquipment

export interface OperativeBriefingBundle {
  kind?: "briefing"
  schema_version?: number
  topic?: string
  case?: unknown
  briefing: OperativeBriefing
  figures?: BriefingFigure[]
  references?: BriefingReference[]
  dossier?: unknown
  provenance: BriefingProvenance
}
