"""Report model for the unified case-board dossier.

Deliberately decoupled from caseprep's CompiledBoard: this is the corrected
presentation contract the renderers consume. Markers carry semantic status only
(evidence axis); there is no confidence axis (defect #2/#3 — dropped by design).
"""

from __future__ import annotations

from dataclasses import dataclass, field


# Status markers (evidence axis). The Unicode glyph renders via the embedded font in
# PDF; the ASCII token is the deterministic fallback (defect #1).
MARK = {"supported": "✓", "verify": "⚠", "quarantine": "✗"}        # ✓ , ⚠ , ✗
ASCII_MARK = {"supported": "[OK]", "verify": "[VERIFY]", "quarantine": "[QUARANTINE]"}
LEGEND_ITEMS = [
    ("supported", "corpus-supported"),
    ("verify", "needs clinician verification"),
    ("quarantine", "off-target — excluded from synthesis"),
]

# Provenance of a board's cards: which Explorer lane produced them and — when the LLM lane
# was requested but not used — why we fell back. Set ONCE at the decision point
# (pipeline._resolve_manifest) and carried to every renderer; never inferred downstream from
# procedure_family (which cannot say *why* the fallback happened).
FALLBACK_BANNER = (
    "Generated by the deterministic rule-based fallback — the AI case-specific Explorer did "
    "not run for this board. Treat the depth as a generic checklist, not case-specific AI "
    "analysis, and verify against primary sources."
)

_SOURCE_LABELS = {
    "llm_generated": "LLM-generated (case-specific)",
    "llm+template": "LLM + curated template",
    "deterministic": "deterministic fallback",
}


@dataclass
class FigureItem:
    fig_id: str                       # stable label, e.g. "F1"
    image_path: str
    caption: str                      # complete caption (#7)
    citation: str = ""                # e.g. "Benzel Spine, p.592"
    relevance: str = ""               # subspecialty-neutral relevance line (#7)
    claim_ref: str | None = None      # short text of the claim it supports (#7 cross-link)


@dataclass
class Claim:
    text: str                         # claim / question, scrubbed (#5: separate from why)
    why: str = ""                     # rationale, rendered on its own indented line (#5)
    status: str = "supported"         # "supported" | "verify" | "quarantine" (coarse marker; renderers consume)
    sub_items: list[str] = field(default_factory=list)   # checkbox sub-items (#6)
    figure_ids: list[str] = field(default_factory=list)  # linked figures (#7 cross-link)
    raw: str | None = None            # original source text used for dedup (#9)
    grade: str = ""                   # fine evidence category (P2 #5, neuro_caseboard.evidence_grade)

    @property
    def dedup_text(self) -> str:
        return self.raw if self.raw is not None else self.text


@dataclass
class Section:
    heading: str
    intro: str = ""
    claims: list[Claim] = field(default_factory=list)
    figures: list[FigureItem] = field(default_factory=list)
    cross_refs: list[str] = field(default_factory=list)   # populated by dedup (#9)
    # Optional contemporary-literature block (case dossier, WS-3): a LiteratureSection-shaped
    # object with `.narrative` + `.citations` ([L#], PMID/DOI). Kept on a SEPARATE axis from the
    # corpus evidence ([n]); duck-typed so model.py stays decoupled from the qa lane.
    literature: object | None = None


@dataclass
class EvidenceSummary:
    """One clean evidence-disposition partition (defect #2: no second axis to
    contradict it). supported + to_verify + quarantined == total cards."""

    supported: int = 0       # corpus-supported
    to_verify: int = 0       # needs_review + no corpus match -> clinician verifies
    quarantined: int = 0     # off-target retrievals, moved to the appendix


@dataclass
class AppendixEntry:
    heading: str
    items: list[str] = field(default_factory=list)     # quarantined claim lines
    sources: list[str] = field(default_factory=list)   # evidence source citations


@dataclass
class Appendix:
    entries: list[AppendixEntry] = field(default_factory=list)

    def is_empty(self) -> bool:
        return not any(e.items or e.sources for e in self.entries)


@dataclass
class Dossier:
    title: str
    summary: EvidenceSummary
    sections: list[Section] = field(default_factory=list)
    appendix: Appendix = field(default_factory=Appendix)
    provenance: "Provenance" = field(default_factory=lambda: Provenance())


@dataclass
class Provenance:
    """Where a board's cards came from. ``degraded`` is True only when the LLM lane was
    requested but the deterministic fallback was used (an explicit ``--no-llm`` run is NOT
    degraded). ``reason``/``detail`` are PHI-safe reason codes — never card or topic text."""

    source: str = "llm_generated"   # one of _SOURCE_LABELS keys
    degraded: bool = False
    reason: str = ""                # "" | "llm_disabled" | "llm_error" | "llm_underproduced"
    detail: str = ""                # e.g. exception type name; never card/topic text

    @property
    def source_label(self) -> str:
        return _SOURCE_LABELS.get(self.source, self.source or "unknown")


def fallback_notice(provenance) -> str | None:
    """Single source of truth for the point-of-use fallback banner copy. Returns the banner
    string when the board silently fell back to the deterministic lane, else None."""
    return FALLBACK_BANNER if getattr(provenance, "degraded", False) else None
