"""Generate web/src/lib/briefingTypes.ts from the OperativeBriefingBundle Pydantic schema.

The browser contract for the briefing surface is generated from the Python schema so it
cannot drift: a pytest (tests/test_briefing_types_gen.py) regenerates in-memory and diffs
against the checked-in file. Run this script to refresh the file after a model change:

    python3 scripts/gen_briefing_types.py

Scope: the Pydantic *core* only. The served JSON augments figures with image_url/
image_available and serializes `case`/`dossier` as opaque (Any -> unknown); those seams
are hand-maintained in web/src/lib/api.ts on top of these generated interfaces.
"""
from __future__ import annotations

from pathlib import Path

from neuro_caseboard.briefing_model import OperativeBriefingBundle

HEADER = (
    "// GENERATED by scripts/gen_briefing_types.py — DO NOT EDIT BY HAND.\n"
    "// Regenerate after a briefing_model.py change: python3 scripts/gen_briefing_types.py\n"
    "// Source of truth: OperativeBriefingBundle.model_json_schema() (Pydantic v2).\n\n"
)


def _ts_type(node: dict) -> str:
    """One JSON-schema node -> a TS type expression. Raises on any construct we don't emit,
    so a new model shape fails the drift-guard test instead of generating silent junk."""
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return f'"{node["const"]}"'
    if "enum" in node:
        return " | ".join(f'"{v}"' for v in node["enum"])
    if "anyOf" in node:
        return " | ".join(_ts_type(s) for s in node["anyOf"])
    if "oneOf" in node:                      # discriminated union (equipment)
        return " | ".join(_ts_type(s) for s in node["oneOf"])
    t = node.get("type")
    if t == "null":
        return "null"
    if t == "array":
        return f"{_ts_type(node['items'])}[]"
    if t == "object":
        # `meta` (additionalProperties) and any other object map to an opaque record.
        return "Record<string, unknown>"
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if not node or set(node) <= {"title", "default"}:   # untyped (Any) prop -> opaque
        return "unknown"
    raise ValueError(f"gen_briefing_types: unhandled schema node {node!r}")


def _interface(name: str, defn: dict) -> str:
    props = defn.get("properties", {})
    required = set(defn.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, node in props.items():
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {_ts_type(node)}")
    lines.append("}")
    return "\n".join(lines)


def generate_ts() -> str:
    schema = OperativeBriefingBundle.model_json_schema()
    out = [HEADER.rstrip("\n")]
    # Named $defs become interfaces. $defs are emitted in sorted order for a stable, diffable file.
    for name, defn in sorted(schema.get("$defs", {}).items()):
        out.append("")
        out.append(_interface(name, defn))
    # Equipment discriminated union -> named alias (read off the OperativeBriefing.equipment prop).
    equip = schema["$defs"]["OperativeBriefing"]["properties"]["equipment"]
    union = next(s for s in equip["anyOf"] if "oneOf" in s)
    members = " | ".join(m["$ref"].rsplit("/", 1)[-1] for m in union["oneOf"])
    out.append("")
    out.append(f"export type EquipmentPlan = {members}")
    # Top-level bundle (its own props: case/dossier are opaque, figures get a view type in api.ts).
    out.append("")
    out.append(_interface("OperativeBriefingBundle", schema))
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    target = Path(__file__).resolve().parent.parent / "web" / "src" / "lib" / "briefingTypes.ts"
    target.write_text(generate_ts())
    print(f"wrote {target}")
